name: CI

on:
    push:
        branches:
            - main
            - dev
            - temp_test_branch  # if in need, create such a temporary branch to test some functions
    pull_request:
        branches:
            - dev

jobs:
    CI-testing:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -l {0}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                python-version: ["3.7", "3.11"]

        steps:
            - name: Check out the repo code
              uses: actions/checkout@v3

            - name: Set up Conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: BrewPOTS-testing
                  python-version: ${{ matrix.python-version }}
                  environment-file: conda-environment.yml
                  auto-activate-base: false

            - name: Fetch the test environment details
              run: |
                  which python
                  conda info
                  conda list

            - name: Test all notebook files
              run: |
                  ipython -c "%run PyPOTS_Imputation.ipynb"
                  ipython -c "%run PyPOTS_Classification.ipynb"
                  ipython -c "%run PyPOTS_Clustering.ipynb"
                  ipython -c "%run PyPOTS_Forecasting.ipynb"
